---

- hosts: all
  become: true
  pre_tasks:

  - name: Dpkg fixing in Ubuntu Servers
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Update and Upgrade remote in Ubuntu servers
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing epel-release and dnf
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade remote CentOS server
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: Ubuntu
  become: true
  roles:
    - Nagios_Ubuntu

- hosts: CentOS
  become: true
  roles:
    - Nagios_CentOS

- hosts: Ubuntu
  become: true
  roles:
    - role: Prometheus_Ubuntu
      source: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz

- hosts: CentOS
  become: true
  roles:
    - role: Prometheus_CentOS
      source: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz

- hosts: ElasticSearch
  tags: es
  become: true
  roles:
    - { role: ElasticSearch, ip_host: 192.168.56.128 }

- hosts: Logstash
  tags: Logstash
  become: true
  roles:
    - role: Logstash
      gpg_key_logstash: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- hosts: Kibana
  tags: Kibana
  become: true
  roles:
    - { role: Kibana, target_ip: 192.168.56.128, ip_host: 192.168.56.130, gpg_key_kibana: https://artifacts.elastic.co/GPG-KEY-elasticsearch }

- hosts: CentOS
  tags: ls
  become: true
  roles:
    - LampStack_CentOS

- hosts: Ubuntu
  tags: ls
  become: true
  roles:
    - LampStack_Ubuntu
